version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: ping-server
    ports:
      - "50051:50051"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: ping-client
    depends_on:
      - server
